// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertBatchTransactions implements pgx.CopyFromSource.
type iteratorForInsertBatchTransactions struct {
	rows                 []InsertBatchTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBatchTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBatchTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Txid,
		r.rows[0].TxHash,
		r.rows[0].Version,
		r.rows[0].Size,
		r.rows[0].Vsize,
		r.rows[0].Weight,
		r.rows[0].Locktime,
		r.rows[0].Fee,
		r.rows[0].BlockHash,
		r.rows[0].Index,
		r.rows[0].InputCount,
		r.rows[0].OutputCount,
		r.rows[0].TotalOutputValue,
	}, nil
}

func (r iteratorForInsertBatchTransactions) Err() error {
	return nil
}

func (q *Queries) InsertBatchTransactions(ctx context.Context, arg []InsertBatchTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"txid", "tx_hash", "version", "size", "vsize", "weight", "locktime", "fee", "block_hash", "index", "input_count", "output_count", "total_output_value"}, &iteratorForInsertBatchTransactions{rows: arg})
}
