// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"github.com/spacesprotocol/explorer-backend/pkg/types"
)

type Block struct {
	Hash           types.Bytes
	Size           int64
	StrippedSize   int64
	Weight         int32
	Height         int32
	Version        int32
	HashMerkleRoot types.Bytes
	Time           int32
	MedianTime     int32
	Nonce          int64
	Bits           types.Bytes
	Difficulty     float64
	Chainwork      types.Bytes
	Orphan         bool
}

type Transaction struct {
	Txid      types.Bytes
	TxHash    *types.Bytes
	Version   int32
	Size      int64
	Vsize     int64
	Weight    int64
	Locktime  int32
	Fee       int64
	BlockHash *types.Bytes
	Index     sql.NullInt32
}

type TxInput struct {
	BlockHash    types.Bytes
	Txid         types.Bytes
	Index        int64
	HashPrevout  types.Bytes
	IndexPrevout int64
	Sequence     int64
	Coinbase     *types.Bytes
	Txinwitness  []types.Bytes
}

type TxOutput struct {
	BlockHash    types.Bytes
	Txid         types.Bytes
	Index        int32
	Value        int64
	Scriptpubkey *types.Bytes
}
