FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache gcc g++ git

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/sync cmd/sync
COPY pkg pkg

RUN go build -o /usr/local/bin/sync ./cmd/sync

CMD ["sync"]
